learning_log/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""Определяет схемы URL для learning_logs."""
 
from django.urls import path
from . import views
 
app_name = 'learning_logs'
urlpatterns = [
    # Домашняя страница
    path('', views.index, name='index'),
    # Страница со списком всех тем.
    path('topics/', views.topics, name='topics'),
    # Страница с подробной информацией по отдельной теме
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Страница для добавления новой темы
    path('new_topic/', views.new_topic, name='new_topic'),
    # Страница для добавления новой записи
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Страница для редактирования записи
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Определяет схемы URL для пользователей"""
 
from django.urls import path, include
from . import views
 
app_name = 'users'
urlpatterns = [
    # Включить URL авторизации по умолчанию.
    path('', include('django.contrib.auth.urls')),
    # Страница регистрации.
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
   """Тема, которую изучает пользователь"""
   text = models.CharField(max_length=200)
   date_added = models.DateTimeField(auto_now_add=True)
   owner = models.ForeignKey(User, on_delete=models.CASCADE)
 
   def __str__(self):
      """Возвращает строковое представление модели."""
      return self.text

class Entry(models.Model):
   """Информация, изученная пользователем по теме"""
   topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
   text = models.TextField()
   date_added = models.DateTimeField(auto_now_add=True)
 
   class Meta:
      verbose_name_plural = 'entries'
 
   def __str__(self):
      """Возвращает строковое представление модели."""
      if len(self.text) > 50:
         return f"{self.text[:50]}..."
      else: 
         return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
 
from .models import Topic, Entry
 
class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.http import Http404

# Create your views here.
def index(request):
    """Домашняя страница приложения Learning Log"""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """Выводит список тем."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Выводит одну тему и все ее записи."""
    topic = Topic.objects.get(id=topic_id)
    # Проверка того, что тема принадлежит текущему пользователю.
    check_topic_owner(request, topic)

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Определяет новую тему."""
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = TopicForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Добавляет новую запись по конкретной теме."""
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(request, topic)
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = EntryForm() 
    else:
        # Отправлены данные POST; обработать данные.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    # Вывести пустую или недействительную форму.
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Редактирует существующую запись."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_topic_owner(request, topic)
    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = EntryForm(instance=entry)
    else:
        # Отправка данных POST; обработать данные.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

def check_topic_owner(request, topic):
    if topic.owner != request.user:
        raise Http404

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
 
def register(request):
    """Регистрирует нового пользователя."""
    if request.method != 'POST':
        # Выводит пустую форму регистрации.
        form = UserCreationForm()
    else:
        # Обработка заполненной формы.
        form = UserCreationForm(data=request.POST)
 
        if form.is_valid():
            new_user = form.save()
            # Выполнение входа и перенаправление на домашнюю страницу.
            login(request, new_user)
            return redirect('learning_logs:index')
            
    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!-- Устанавливает тип документа -->
<!doctype html>
<!-- Устанавливает язык документа -->
<html lang="en">
  <head>
    <!-- Устанавливает кодировку, позволяющую использовать знаки разных языков -->
    <meta charset="utf-8">
    <!-- Устанавливает настройки маштабирования на разных устройствах -->
    <meta name="viewport" content="width=device-width, initial-scale=1,
      shrink-to-fit=no">
      <!-- Заголовок -->
    <title>Learning Log</title>
    <!-- Загружает необходимые библиотеки  -->
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
 
  </head>
    <body>
      <!-- navbar - Указывает, что это настройки навигационной панели -->
      <!-- navbar-expand-md - Указывает размер экрана при котором панель станет раскрывающимся списком -->
      <!-- navbar-dark bg-dark Устанавливает тёмную тему для панели -->
      <!-- mb-4 border - Делает отступ -->
      <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 border">
        <!-- Делает ссылку выделяемой на фоне других -->
        <a class="navbar-brand" href="{% url 'learning_logs:index'%}">
            Learning Log</a>
        <!-- Задаёт настройки выпадающего списка -->
        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'learning_logs:topics'%}">
                Topics</a></li>
          </ul>
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <span class="navbar-text">Hello, {{ user.username }}.</span>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
            {% endif %}
          </ul>
        </div>
   
      </nav>
      <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
          {% block page_header %}{% endblock page_header %}
        </div>
        <div>
          {% block content %}{% endblock content %}
        </div>
      </main>
 
    </body>
    </html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block content %}
  <p><h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2></p>

  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Save changes</button>
    {% endbuttons %}
  </form>
 
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
 
{% block page_header %}
  <div class='jumbotron'>
    <h1 class="display-3">Track your learning.</h1>
    <p class="lead">Make your own Learning Log, and keep a list of the
      topics you're learning about. Whenever you learn something new
      about a topic, make an entry summarizing what you've learned.</p>
    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
      role="button">Register &raquo;</a>
  </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2>You can add a new entry here:</h2>
{% endblock page_header %}

{% block content %}
 
  <p><h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2></p>

  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Add entry</button>
    {% endbuttons %}
  </form>
 
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2>You can add a new topic here:</h2>
{% endblock page_header %}

{% block content %}
 
  <form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Add topic</button>
    {% endbuttons %}
  </form>
 
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}

  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
  </p>
  <ul>
  {% for entry in entries %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
          Edit entry</a></small>
      </h4>
      <div class="card-body">
        {{ entry.text|linebreaks }}
      </div>
  {% empty %}
    <p>There are no entries for this topic yet.</p>
  {% endfor %}
  </ul>
 
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h1>Topics</h1>
{% endblock page_header %}

{% block content %}

  <ul>
    {% for topic in topics %}
      <li><h3>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
      </h3></li>
    {% empty %}
      <li><h3>No topics have been added yet.</h3></li>
    {% endfor %}
  </ul>
  
  <h3><a href="{% url 'learning_logs:new_topic' %}">Add new topic</h3>

{% endblock content %}